services:
  app:
    image: my-app-dev
    build:
      context: ./frontend # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./frontend/:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    container_name: my-app-dev # This will name the container my-app-dev
  server:
    image: myapp-backend-development
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
     - ./backend/:/usr/src/app
    container_name: myapp-backend-dev
    environment:
      MONGODB_URI: ${MONGODB_URI}
      TEST_MONGODB_URI: ${TEST_MONGODB_URI}
      SECRET: ${SECRET}
      PORT: ${PORT}
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server

